<?php

namespace IMS\Security;

use IMS\Security\Type;
use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

class SecurityClassmap
{

    public static function getCollection() : \Phpro\SoapClient\Soap\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection([
            new ClassMap('OperatorInfoType', Type\OperatorInfoType::class),
            new ClassMap('TimeZoneType', Type\TimeZoneType::class),
            new ClassMap('LanguageType', Type\LanguageType::class),
            new ClassMap('BranchType', Type\BranchType::class),
            new ClassMap('HeldPrivilegeType', Type\HeldPrivilegeType::class),
            new ClassMap('HeldRoleType', Type\HeldRoleType::class),
            new ClassMap('RoleType', Type\RoleType::class),
            new ClassMap('OperatorDetailsType', Type\OperatorDetailsType::class),
            new ClassMap('FloatCodeSummaryType', Type\FloatCodeSummaryType::class),
            new ClassMap('FloatCodeInfoType', Type\FloatCodeInfoType::class),
            new ClassMap('BranchSummaryType', Type\BranchSummaryType::class),
            new ClassMap('BranchInfoType', Type\BranchInfoType::class),
            new ClassMap('DepartmentSummaryType', Type\DepartmentSummaryType::class),
            new ClassMap('DepartmentInfoType', Type\DepartmentInfoType::class),
            new ClassMap('DepartmentTypeInfoType', Type\DepartmentTypeInfoType::class),
            new ClassMap('IlsLocationSummaryType', Type\IlsLocationSummaryType::class),
            new ClassMap('IlsLocationInfoType', Type\IlsLocationInfoType::class),
            new ClassMap('IlsSublocationSummaryType', Type\IlsSublocationSummaryType::class),
            new ClassMap('IlsSublocationInfoType', Type\IlsSublocationInfoType::class),
            new ClassMap('CollectionSummaryType', Type\CollectionSummaryType::class),
            new ClassMap('CollectionInfoType', Type\CollectionInfoType::class),
            new ClassMap('DiscardReasonSummaryType', Type\DiscardReasonSummaryType::class),
            new ClassMap('DiscardReasonInfoType', Type\DiscardReasonInfoType::class),
            new ClassMap('MaterialTypeSummaryType', Type\MaterialTypeSummaryType::class),
            new ClassMap('MaterialTypeInfoType', Type\MaterialTypeInfoType::class),
            new ClassMap('SortingPointInfoType', Type\SortingPointInfoType::class),
            new ClassMap('ChuteType', Type\ChuteType::class),
            new ClassMap('StatusType', Type\StatusType::class),
            new ClassMap('ParameterType', Type\ParameterType::class),
            new ClassMap('CategoryDistributionRuleInfoType', Type\CategoryDistributionRuleInfoType::class),
            new ClassMap('CategoryInfoType', Type\CategoryInfoType::class),
            new ClassMap('LocationUsageType', Type\LocationUsageType::class),
            new ClassMap('LocationType', Type\LocationType::class),
            new ClassMap('BranchConfigurationInfoType', Type\BranchConfigurationInfoType::class),
            new ClassMap('FineSortingInfoType', Type\FineSortingInfoType::class),
            new ClassMap('PlacementTypeInfoType', Type\PlacementTypeInfoType::class),
            new ClassMap('FloatCodeConfigInfoType', Type\FloatCodeConfigInfoType::class),
            new ClassMap('MaterialGroupingSpecInfoType', Type\MaterialGroupingSpecInfoType::class),
            new ClassMap('MaterialGroupingInfoType', Type\MaterialGroupingInfoType::class),
            new ClassMap('MaterialGroupingWithSpecInfoType', Type\MaterialGroupingWithSpecInfoType::class),
            new ClassMap('PeriodicalInfoType', Type\PeriodicalInfoType::class),
            new ClassMap('FineSortingAndTransportUnitInfoType', Type\FineSortingAndTransportUnitInfoType::class),
            new ClassMap('FineSortingDistributionInfoType', Type\FineSortingDistributionInfoType::class),
            new ClassMap('TransportUnitInfoType', Type\TransportUnitInfoType::class),
            new ClassMap('ChuteInfoType', Type\ChuteInfoType::class),
            new ClassMap('HistoryInfoType', Type\HistoryInfoType::class),
            new ClassMap('ItemInfoType', Type\ItemInfoType::class),
            new ClassMap('DestinationTypeInfoType', Type\DestinationTypeInfoType::class),
            new ClassMap('RouteInfoType', Type\RouteInfoType::class),
            new ClassMap('ParameterInfoType', Type\ParameterInfoType::class),
            new ClassMap('PickPlacementInfoType', Type\PickPlacementInfoType::class),
            new ClassMap('SimpleMaterialGroupingInfoType', Type\SimpleMaterialGroupingInfoType::class),
            new ClassMap('SimpleLocationInfoType', Type\SimpleLocationInfoType::class),
            new ClassMap('ClassificationGroupInfoType', Type\ClassificationGroupInfoType::class),
            new ClassMap('ExtendedBranchInfoType', Type\ExtendedBranchInfoType::class),
            new ClassMap('LocationNodeType', Type\LocationNodeType::class),
            new ClassMap('ExtendedBibliographicRecordInfoType', Type\ExtendedBibliographicRecordInfoType::class),
            new ClassMap('ExtendedItemInfoType', Type\ExtendedItemInfoType::class),
            new ClassMap('BibliographicRecordInfoType', Type\BibliographicRecordInfoType::class),
            new ClassMap('SimpleCategoryInfoType', Type\SimpleCategoryInfoType::class),
            new ClassMap('PlacementInfoType', Type\PlacementInfoType::class),
            new ClassMap('SimpleSortingPointInfoType', Type\SimpleSortingPointInfoType::class),
            new ClassMap('MaterialWidthWithPageCountInfoType', Type\MaterialWidthWithPageCountInfoType::class),
            new ClassMap('MaterialWidthWithoutPageCountInfoType', Type\MaterialWidthWithoutPageCountInfoType::class),
            new ClassMap('PlacementTypePriorityInfoType', Type\PlacementTypePriorityInfoType::class),
            new ClassMap('MaterialGroupingSpecSumInfoType', Type\MaterialGroupingSpecSumInfoType::class),
            new ClassMap('PickOrderInfoType', Type\PickOrderInfoType::class),
            new ClassMap('RequisitionInfoType', Type\RequisitionInfoType::class),
            new ClassMap('RequisitionTypeType', Type\RequisitionTypeType::class),
            new ClassMap('BasicTransactionInfoType', Type\BasicTransactionInfoType::class),
            new ClassMap('OperatorBasicInfoType', Type\OperatorBasicInfoType::class),
            new ClassMap('TransactionTypeType', Type\TransactionTypeType::class),
            new ClassMap('ItemHistoryEntryType', Type\ItemHistoryEntryType::class),
            new ClassMap('RequisitionHistoryEntryType', Type\RequisitionHistoryEntryType::class),
            new ClassMap('RequisitionDetailsType', Type\RequisitionDetailsType::class),
            new ClassMap('IlsStatusType', Type\IlsStatusType::class),
            new ClassMap('ParameterGroupType', Type\ParameterGroupType::class),
            new ClassMap('AssignmentTypeInfoType', Type\AssignmentTypeInfoType::class),
            new ClassMap('AssignmentInfoType', Type\AssignmentInfoType::class),
            new ClassMap('BibliographicRecordHistoryEntryType', Type\BibliographicRecordHistoryEntryType::class),
            new ClassMap('BibrecLifecycleRuleInfoType', Type\BibrecLifecycleRuleInfoType::class),
            new ClassMap('ExhibitionGroupingInfoType', Type\ExhibitionGroupingInfoType::class),
            new ClassMap('SimpleExhibitionInfoType', Type\SimpleExhibitionInfoType::class),
            new ClassMap('ExhibitionInfoType', Type\ExhibitionInfoType::class),
            new ClassMap('ExhibitionDetailsInfoType', Type\ExhibitionDetailsInfoType::class),
            new ClassMap('ExhibitionGroupingDetailsInfoType', Type\ExhibitionGroupingDetailsInfoType::class),
            new ClassMap('ExhibitionGroupingSpecInfoType', Type\ExhibitionGroupingSpecInfoType::class),
            new ClassMap('PickOrderClassInfoType', Type\PickOrderClassInfoType::class),
            new ClassMap('PickOrderTypeInfoType', Type\PickOrderTypeInfoType::class),
            new ClassMap('NamedListSummaryType', Type\NamedListSummaryType::class),
            new ClassMap('PickOrderSummaryType', Type\PickOrderSummaryType::class),
            new ClassMap('PickOrderDetailsType', Type\PickOrderDetailsType::class),
            new ClassMap('Login', Type\Login::class),
            new ClassMap('LoginResponse', Type\LoginResponse::class),
            new ClassMap('Logout', Type\Logout::class),
            new ClassMap('LogoutResponse', Type\LogoutResponse::class),
            new ClassMap('ChangePassword', Type\ChangePassword::class),
            new ClassMap('ChangePasswordResponse', Type\ChangePasswordResponse::class),
            new ClassMap('GetOperatorForToken', Type\GetOperatorForToken::class),
            new ClassMap('GetOperatorForTokenResponse', Type\GetOperatorForTokenResponse::class),
            new ClassMap('GetPrivileges', Type\GetPrivileges::class),
            new ClassMap('GetPrivilegesResponse', Type\GetPrivilegesResponse::class),
            new ClassMap('GetBranchesWithPrivilege', Type\GetBranchesWithPrivilege::class),
            new ClassMap('GetBranchesWithPrivilegeResponse', Type\GetBranchesWithPrivilegeResponse::class),
            new ClassMap('CheckPrivilege', Type\CheckPrivilege::class),
            new ClassMap('CheckPrivilegeResponse', Type\CheckPrivilegeResponse::class),
            new ClassMap('validateToken', Type\ValidateToken::class),
            new ClassMap('validateTokenResponse', Type\ValidateTokenResponse::class),
            new ClassMap('PutOperatorLog', Type\PutOperatorLog::class),
            new ClassMap('PutOperatorLogResponse', Type\PutOperatorLogResponse::class),
        ]);
    }


}

